resolver: lts-19.28
packages:
- .
ghc-options:
  "$locals":
    -Wall -Wcompat -Werror -Widentities
    -Wincomplete-record-updates -Wincomplete-uni-patterns
    -Wmissing-home-modules -Wmissing-export-lists -Wpartial-fields
    -Wredundant-constraints -Wunused-packages -Wmissing-deriving-strategies
extra-deps:
- annotated-exception-0.2.0.4@sha256:3d499515d64d64ecc1a43a8ebbc70b24020e1ed2cbf8726039d282d87d8cb0ed,1785
- env-guard-0.2@sha256:59410eed9b9ddbd115760a59c7170927320d8612e414701d323a0c8985c97523,1251
- package-version-0.1.0.0@sha256:bb9fc93e905540aa8e1b32f80c2dc82756a4481c63779bd92e3796ed8085ab98,2854
- git: https://github.com/tbidne/algebra-simple.git
  commit: 2c8a79e8d3bf67c99e4851c557bf68a44c512307
- git: https://github.com/tbidne/bounds.git
  commit: 004f03aec46f29069fd0bf5115a384cd2b3141b3
- git: https://github.com/tbidne/byte-types.git
  commit: be3e764d76c530fd3641c133ed2d53adfc8f046d
- git: https://github.com/tbidne/monad-effects.git
  commit: 3fddc571755e7b01a0c665058e9e0503b5c07250
  subdirs:
  - monad-callstack
- git: https://github.com/tbidne/smart-math.git
  commit: e88d85948eb7de24ebb567ca10e06257fc5dbd49
- git: https://github.com/tbidne/time-conv.git
  commit: 147a0b9f98e8bf558735cf49c63071564d11681f
flags:
  refined:
    aeson: false
    quickcheck: false
nix:
  shell-file: nix/stack.nix