resolver: lts-19.4
packages:
- .

ghc-options:
  "$locals":
    -Wall -Wcompat -Werror -Widentities
    -Wincomplete-record-updates -Wincomplete-uni-patterns
    -Wmissing-home-modules -Wmissing-export-lists -Wpartial-fields
    -Wredundant-constraints -Wunused-packages -Wmissing-deriving-strategies

extra-deps:
- package-version-0.1.0.0@sha256:bb9fc93e905540aa8e1b32f80c2dc82756a4481c63779bd92e3796ed8085ab98,2854
- git: https://github.com/tbidne/algebra-simple.git
  commit: 2a020dbe0290abe57af31c5011a3a18ff17dcec9
- git: https://github.com/tbidne/byte-types.git
  commit: e1f2f889ede098b8c7682db1504a831f81c98c3d
- git: https://github.com/tbidne/smart-math.git
  commit: 5caef04d86f808aa22cc5560263f10e198e1de1c

flags:
  refined:
    aeson: false
    quickcheck: false

nix:
  shell-file: nix/stack.nix
