name: cabal

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
  
  workflow_dispatch:

jobs:
  cabal:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup nix
        uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/31ffc50c571e6683e9ecc9dbcbd4a8e9914b4497.tar.gz

      - name: Compile
        # No --pure because we need git to clone the non-hackage dependency,
        # and if we try to add git to ci.nix then we some kind of SSL
        # certificate problem.
        run: nix-shell ci.nix --command "cabal update && cabal build"
