name: "cabal"

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  cabal:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: ["8.10.7", "9.0.2", "9.2.3"]
    steps:
      - uses: actions/checkout@v3.0.2

      - uses: haskell/actions/setup@v2.0.0
        with:
          ghc-version: ${{ matrix.ghc }}

      - name: Compile
        run: cabal build

      - name: Unit Tests
        run: cabal test unit