name: "cabal"

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  cabal:
    strategy:
      fail-fast: false
      matrix:
        ghc:
          - "8.10.7"
          - "9.0.2"
          - "9.2.7"
          - "9.4.4"
        os:
          - "macos-latest"
          - "ubuntu-latest"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3.3.0

      - uses: haskell/actions/setup@v2.3.4
        with:
          ghc-version: ${{ matrix.ghc }}

      - name: Compile
        run: cabal build

      - name: Doc Tests
        run : |
          cabal configure \
            --enable-tests \
            --write-ghc-environment-files always
          cabal build
          RUN_DOCTEST=1 cabal test doctest

      - name: Unit Tests
        run: cabal test unit