name: nix

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
  
  workflow_dispatch:

jobs:
  nix:
    strategy:
      fail-fast: false
      matrix:
        platform:
        - "macos-latest"
        - "ubuntu-latest"
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3.3.0

      - name: Setup nix
        uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/b39924fc7764c08ae3b51beef9a3518c414cdb7d.tar.gz
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      
      - name: Compile & Test
        run: |
          nix build
          if [ -d "./result/lib" ]; then
            echo "Build succeeded"
          else
            echo "Build failed"
            exit -1
          fi
