name: nix

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
  
  workflow_dispatch:

jobs:
  nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2

      - name: Setup nix
        uses: cachix/install-nix-action@v17
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      
      - name: Compile & Test
        run: |
          nix build
          if [ -d "./result/lib" ]; then
            echo "Build succeeded"
          else
            echo "Build failed"
            exit -1
          fi
