name: "stack_nightly"

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  stack_nightly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2

      - name: Setup nix
        uses: cachix/install-nix-action@v17
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Compile
        run: |
          nix-shell nix/stack_nightly.nix --command \
            "stack update && stack build --nix --ghc-options -Werror"

      - name: Test
        run: |
          nix-shell nix/stack_nightly.nix --command \
            "stack update && stack test --nix --ghc-options -Werror"